a = ['athkalia-Just-Another-Android-App.', 'udacity-Sunshine-Version-2.', 'facebook-rebound.',
     'kaushikgopal-RxJava-Android-Samples.', 'ozodrukh-RippleDrawable.', 'apache-groovy.',
     'daimajia-AndroidSwipeLayout.', 'apache-kafka.', 'apl-devs-AppIntro.', 'zyyoona7-EasyPopup.', 'auth0-java-jwt.',
     'facebook-facebook-android-sdk.', 'traex-CalendarListview.', 'apache-aurora.', 'smuyyh-ImageSelector.',
     'jaredrummler-AnimatedSvgView.', 'airbnb-aerosolve.', 'hanhailong-FlowTag.', 'bcgit-bc-java.',
     'traex-ExpandableLayout.', 'orhanobut-dialogplus.', 'scottyab-showhidepasswordedittext.', 'lyft-scoop.',
     'jhusain-learnrxjava.', 'airbnb-airpal.', 'xujinyang-BiuEditText.', 'facebook-react-native.',
     'mancj-SlideUp-Android.', 'facebook-stetho.', 'karonl-InDoorSurfaceView.', 'orhanobut-hawk.',
     'airbnb-DeepLinkDispatch.', 'airbnb-lottie-android.', 'daimajia-EverMemo.', 'naman14-AlgorithmVisualizer-Android.',
     'facebook-buck.', 'facebook-fresco.', 'AAkira-ExpandableLayout.', 'gjiazhe-PanoramaImageView.',
     'Hitomis-FunGameRefresh.', 'carlonzo-StikkyHeader.', 'mongodb-morphia.', 'dmytrodanylyk-android-process-button.',
     'dkim0419-SoundRecorder.', 'flavioarfaria-KenBurnsView.', 'qdrzwd-VideoRecorder.', 'UnderwaterApps-overlap2d.',
     'facebook-TextLayoutBuilder.', 'apache-geode.', 'apache-ofbiz.', 'traex-RippleEffect.',
     'facebook-network-connection-class.', 'facebook-shimmer-android.', 'dmytrodanylyk-circular-progress-button.',
     'facebook-device-year-class.', 'pahimar-Equivalent-Exchange-3.', 'daimajia-AndroidImageSlider.',
     'nimengbo-StickerView.', 'psaravan-JamsMusicPlayer.', 'daimajia-AndroidViewAnimations.', 'orhanobut-logger.',
     'TakeoffAndroid-AppIntroAnimation.', 'smuyyh-SprintNBA.', 'jenzz-Android-UndoBar.', 'jdamcd-android-crop.',
     'anton46-Android-StepsView.', 'jenzz-Android-MaterialPreference.', 'orhanobut-wasp.',
     'saiwu-bigkoo-Android-SVProgressHUD.', 'dersoncheng-MultipleTheme.', 'airbnb-RxGroups.', 'sgroschupf-zkclient.',
     'kaichunlin-android-transition.', 'Haehnchen-idea-php-symfony2-plugin.', 'inmite-android-validation-komensky.',
     'mongodb-mongo-hadoop.', 'daimajia-NumberProgressBar.', 'Lauzy-LBehavior.', 'airbnb-epoxy.',
     'ozodrukh-CircularReveal.', 'facebook-conceal.', 'facebook-screenshot-tests-for-android.', 'facebook-litho.',
     'naman14-MaterialPowerMenu.', 'airbnb-native-navigation.', 'xiaoyaoyou1212-BLE.', 'cbeust-testng.',
     'jeasonlzy-okhttp-OkGo.', 'airbnb-AirMapView.', 'aryarohit07-PicassoFaceDetectionTransformation.',
     'halysongoncalves-Pugnotification.', 'Almeros-android-gesture-detectors.', 'daimajia-AnimationEasingFunctions.',
     'airbnb-lottie-react-native.', 'Idtk-SmallChart.', 'dmytrodanylyk-shadow-layout.', 'MartinRGB-GiftCard-Android.',
     'cbeust-jcommander.', 'saiwu-bigkoo-Android-ConvenientBanner.', 'Chainfire-libsuperuser.', 'tcking-GiraffePlayer.',
     'jaredrummler-AndroidProcesses.', 'daimajia-AndroidViewHover.', 'Hitomis-transferee.',
     'mongodb-mongo-java-driver.', 'jeasonlzy-NineGridView.', 'scottyab-secure-preferences.', 'MrEngineer13-SnackBar.',
     'eoinfogarty-Onboarding.', 'naman14-Timber.', 'daimajia-AnimeTaste.', 'xiongwei-git-AndroidVideoPlayer.',
     'shehabic-Droppy.', 'saiwu-bigkoo-Android-AlertView.', 'noties-Scrollable.', 'jeasonlzy-ImagePicker.',
     'lyft-scissors.', 'apache-beam.', 'dmilicic-Android-Clean-Boilerplate.', 'worldline-FoldableLayout.',
     'gcacace-android-signaturepad.', 'bmarrdev-android-DecoView-charting.', 'Jasonette-JASONETTE-Android.',
     'real-logic-simple-binary-encoding.', 'Piasy-BigImageViewer.', 'ShamylZakariya-FlyoutMenus.', 'real-logic-agrona.',
     'MizzleDK-Mizuu.', 'Rajawali-Rajawali.', 'ShamylZakariya-StickyHeaders.', 'real-logic-aeron.',
     'jiang111-IndexRecyclerView.', 'steelkiwi-cropiwa.', 'crazycodeboy-TakePhoto.', 'Piasy-AndroidTDDBootStrap.',
     'MummyDing-Leisure.', 'north2016-T-MVP.', 'Brioal-SwipeMenuDemo.', 'emilsjolander-sprinkles.',
     'pnikosis-materialish-progress.', 'DaxiaK-MyDiary.', 'chentao0707-SimplifyReader.',
     'go-lang-plugin-org-go-lang-idea-plugin.', 'lsjwzh-RecyclerViewPager.', 'InQBarna-TableFixHeaders.',
     'emilsjolander-StickyListHeaders.', 'Wrdlbrnft-Searchable-RecyclerView-Demo.', 'jdeferred-jdeferred.',
     'stanfordnlp-CoreNLP.', 'emilsjolander-StickyScrollViewItems.', 'Yasic-QQBubbleView.',
     'lsjwzh-MaterialLoadingProgressBar.', 'emilsjolander-android-FlipView.',
     'rudsonlive-NavigationDrawer-MaterialDesign.', 'evrencoskun-TableView.', 'whilu-AndroidTagView.',
     'JustZak-DilatingDotsProgressBar.', 'instacart-truetime-android.', 'hongyangAndroid-AndroidAutoLayout.',
     'lovedise-PermissionGen.', 'truizlop-SectionedRecyclerView.', 'hongyangAndroid-ChangeSkin.',
     'tbruyelle-RxPermissions.', 'XunMengWinter-CircularAnim.', 'liuling07-SimpleNews.', 'mwolfson-android-historian.',
     'hongyangAndroid-AndroidChangeSkin.', 'truizlop-FABRevealLayout.', 'hongyangAndroid-Android-StickyNavLayout.',
     'ImangazalievM-CircleMenu.', 'hongyangAndroid-FlowLayout.', 'yadav-rahul-TastyToast.', 'alorma-TimelineView.',
     'tjerkw-Android-SlideExpandableListView.', 'Skykai521-StickerCamera.', 'linglongxin24-DylanStepCount.',
     'rholder-guava-retrying.', 'Jungerr-GridPasswordView.', 'hongyangAndroid-okhttputils.',
     'hongyangAndroid-android-percent-support-extend.', 'google-cameraview.', 'google-flexbox-layout.',
     'bingoogolapple-BGABanner-Android.', 'voldemort-voldemort.', 'hongyangAndroid-baseAdapter.', 'google-grafika.',
     'google-ExoPlayer.', 'google-volley.', 'google-santa-tracker-android.', 'hongyangAndroid-Highlight.',
     'pwittchen-ReactiveNetwork.', 'hongyangAndroid-Android_Blog_Demos.', 'google-hover.', 'limedroid-XDroidMvp.',
     'google-iosched.', 'google-google-authenticator-android.', 'google-re2j.', 'google-binnavi.',
     'Krupen-AutoplayVideos.', 'spring-projects-spring-integration-samples.', 'kingideayou-SlideBottomPanel.',
     'spring-projects-spring-android.', 'spring-projects-spring-social.', 'spring-projects-spring-integration.',
     'spring-projects-spring-security.', 'norbsoft-android-typeface-helper.', 'jgilfelt-chuck.',
     'bingoogolapple-BGAQRCode-Android.', 'bingoogolapple-BGASwipeBackLayout-Android.',
     'jgilfelt-android-sqlite-asset-helper.', 'bingoogolapple-BGABadgeView-Android.', 'kingideayou-TagCloudView.',
     'jgilfelt-SystemBarTint.', 'spring-projects-spring-restdocs.', 'spring-projects-spring-loaded.',
     'spring-projects-spring-hadoop.', 'bingoogolapple-BGARefreshLayout-Android.', 'geeeeeeeeek-WeChatLuckyMoney.',
     'Nightonke-JellyToggleButton.', 'andyxialm-SmoothCheckBox.', 'tajchert-Nammu.', 'Kaopiz-KProgressHUD.',
     'fredericojssilva-ShowTipsView.', 'Kaopiz-android-segmented-control.', 'Nightonke-CoCoin.',
     'brianwernick-ExoMedia.', 'spring-projects-spring-batch.', 'spring-projects-spring-session.',
     'Jude95-RollViewPager.', 'Jude95-SwipeBackHelper.', 'codekidX-storage-chooser.', 'byteam-SuperAdapter.',
     'wedcel-DragExpandGrid.', 'Jude95-EasyRecyclerView.', 'alt236-Bluetooth-LE-Library---Android.',
     'dommerq-SuperListview.', 'spring-projects-spring-framework.', 'tajchert-WaitingDots.',
     'mzgreen-HideOnScrollExample.', 'ccrama-Slide.', 'Ajian-studio-GADownloading.', 'wealthfront-magellan.',
     'todotxt-todo.txt-android.', 'kabouzeid-Phonograph.', 'byoutline-kickmaterial.', 'Shinelw-ColorArcProgressBar.',
     'JeroenMols-LandscapeVideoCamera.', 'hejunlin2013-TVSample.', 'permissions-dispatcher-PermissionsDispatcher.',
     'mattprecious-telescope.', 'kickstarter-android-oss.', 'imbryk-LoopingViewPager.', 'Jude95-Beam.',
     'QuadFlask-colorpicker.', 'kevin-wayne-algs4.', 'gejiaheng-Protein.', 'davideas-FlexibleAdapter.',
     'hejunlin2013-DragVideo.', 'ApmeM-android-flowlayout.', 'mttkay-ignition.', 'OnlyInAmerica-GlanceReader.',
     'Luolc-EmojiRain.', 'wingjay-BlurImageView.', 'kaedea-android-mvp-pattern.', 'kaedea-android-tagview.',
     'erikwt-PullToRefresh-ListView.', 'puniverse-quasar.', 'Syehunter-MaterialPageStateLayout.',
     'huazhiyuan2008-RecyclerViewCardGallery.', 'riggaroo-MaterialIntroTutorial.', 'tozny-java-aes-crypto.',
     'grails-grails-core.', 'hujiaweibujidao-FabDialogMorph.', 'linsea-UniversalVideoView.', 'sleekbyte-tailor.',
     'leolin310148-ShortcutBadger.', 'zaihuishou-ExpandableRecyclerview.', 'hsz-idea-gitignore.',
     'shellljx-TagViewGroup.', 'SandroMachado-openalpr-android.', 'mxn21-FlowingDrawer.',
     'zzz40500-Android-PullToNextLayout.', 'mxn21-SlidingCard.', 'tomakehurst-wiremock.',
     'Rogero0o-PasswordLoadingView.', 'zzz40500-android-shapeLoadingView.', 'nuuneoi-Lab-Android-DesignLibrary.',
     'zzz40500-GsonFormat.', 'Rogero0o-MatchView.', 'Narfss-ParallaxEverywhere.', 'multidots-android-app-common-tasks.',
     'zzz40500-AndroidSweetSheet.', 'guardianproject-haven.', 'blipinsk-RecyclerViewHeader.', 'iMeiji-Toutiao.',
     'bookdash-bookdash-android-app.', 'zzz40500-Tinker_imitator.', 'Pixplicity-MultiViewPager.', 'ukanth-afwall.',
     'liaohuqiu-android-cube-app.', 'CyberAgent-android-gpuimage.', 'liaohuqiu-leakcanary-demo.', 'jenly1314-KingTV.',
     'androidmalin-RengwuxianRxjava.', 'Cutta-GifView.', 'balysv-material-menu.', 'palantir-atlasdb.',
     'liaohuqiu-cube-sdk.', 'material-components-material-components-android.', 'fookwood-Launcher3.',
     'blackfizz-EazeGraph.', 'EnterpriseQualityCoding-FizzBuzzEnterpriseEdition.', 'MagicMashRoom-SuperCalendar.',
     'balysv-material-ripple.', 'oubowu-OuNews.', 'liaohuqiu-android-Ultra-Pull-To-Refresh.',
     'jjobes-SlideDateTimePicker.', 'shichaohui-AnimRefreshRecyclerView.', 'chrisbanes-philm.',
     'liaohuqiu-android-UCToast.', 'dongjunkun-DropDownMenu.', 'whataa-SuitLines.', 'p6spy-p6spy.',
     'chrisbanes-ActionBar-PullToRefresh.', 'liaohuqiu-android-GridViewWithHeaderAndFooter.', 'rockerhieu-emojicon.',
     'IsseiAoki-SimpleCropView.', 'jonfinerty-Once.', 'jfoenixadmin-JFoenix.', 'googlemaps-android-maps-utils.',
     'StylingAndroid-Prism.', 'SilenceIM-Silence.', 'esoxjem-MovieGuide.', 'moezbhatti-qksms.',
     'chrisbanes-cheesesquare.', 'dongjunkun-GanK.', 'sourcey-materiallogindemo.', 'chrisbanes-PhotoView.',
     'linkedin-cruise-control.', 'linkedin-databus.', 'jarlen-PhotoEditDemo.', 'googlemaps-google-maps-services-java.',
     'igniterealtime-Smack.', 'linkedin-kafka-monitor.', 'linkedin-dexmaker.', 'bitcoinj-bitcoinj.',
     'DreaminginCodeZH-MaterialRatingBar.', 'GoodieBag-CarouselPicker.', 'linkedin-ambry.', 'linkedin-WhereHows.',
     'leventov-Koloboke.', 'DreaminginCodeZH-MaterialProgressBar.', 'wordpress-mobile-WordPress-Android.',
     'linkedin-rest.li.', 'linkedin-flashback.', 'DreaminginCodeZH-PatternLock.', 'linkedin-PalDB.',
     'linkedin-test-butler.', 'edmodo-cropper.', 'Eajy-MaterialDesignDemo.', 'Todd-Davies-ProgressWheel.',
     'Chanven-CommonPullToRefresh.', 'linkedin-FeatureFu.', 'SlimeKnights-TinkersConstruct.', 'uPhyca-stetho-realm.',
     'kanytu-android-parallax-recyclerview.', 'kanytu-android-material-drawer-template.', 'badoualy-morphy-toolbar.',
     'vmihalachi-turbo-editor.', 'SimpleMobileTools-Simple-Calendar.', 'huntermr-FastAndroid.', 'yrom-ScreenRecorder.',
     'JeasonWong-ElemeShoppingView.', 'linkedin-cleo.', 'mingjunli-GithubApp.', 'amulyakhare-TextDrawable.',
     'JMPergar-AwesomeText.', 'edmodo-range-bar.', 'mikepenz-Android-Iconics.', 'functionaljava-functionaljava.',
     'stealthcopter-AndroidNetworkTools.', 'SalomonBrys-ANR-WatchDog.', 'lguipeng-BubbleView.',
     'qifengdeqingchen-SeatTable.', 'makovkastar-FloatingActionButton.', 'mikepenz-FastAdapter.',
     'mikepenz-wallsplash-android.', 'mikepenz-LollipopShowcase.', 'mikepenz-MaterialDrawer.',
     'mikepenz-Android-ActionItemBadge.', 'futuresimple-android-floating-action-button.', 'Solartisan-WaveSideBar.',
     'lguipeng-Notes.', 'emmaguy-clean-status-bar.', 'faruktoptas-FancyShowCaseView.', 'TeamNewPipe-NewPipe.',
     'lovetuzitong-MultiImageSelector.', 'dreamhead-moco.', 'Manabu-GT-EtsyBlur.', 'ImKarl-CharacterPickerView.',
     'erickok-transdroid.', 'android-cjj-Android-MaterialRefreshLayout.', 'hdodenhof-CircleImageView.',
     'Manabu-GT-ExpandableTextView.', 'TakWolf-CNode-Material-Design.', 'sahildave-Search-View-Layout.', 'mthli-Slice.',
     'wenhuaijun-SearchPictureTool.', 'novoda-android-demos.', 'boycy815-PinchImageView.', 'owncloud-android.',
     'android-cjj-BeautifulRefreshLayout.', 'Subito-it-Masaccio.', 'oblac-jodd.', 'mthli-Knife.',
     'Androguide-HoloGraphLibrary.', 'mikepenz-AboutLibraries.', 'wiztools-rest-client.', 'Clans-FloatingActionButton.',
     'LuckyJayce-LargeImage.', 'nkzawa-socket.io-android-chat.', 'iammert-MusicPlayerView.',
     'imallan-JellyRefreshLayout.', 'nbsp-team-MaterialFilePicker.', 'iammert-ProgressLayout.', 'SimonVT-schematic.',
     'LuckyJayce-MVCHelper.', '2dxgujun-AndroidTagGroup.', 'SimonVT-android-menudrawer.', 'iammert-StatusView.',
     'bin456789-Unblock163MusicClient-Xposed.', 'iammert-MaterialIntroView.', 'SimonVT-MessageBar.',
     'iammert-InteractivePlayerView.', 'CalebFenton-simplify.', 'jingle1267-android-utils.', 'cpoopc-ScrollableLayout.',
     'LuckyJayce-ViewPagerIndicator.', 'nkzawa-socket.io-android-chat.', 'patrickfav-Dali.', 'termux-termux-app.',
     'Bilibili-BiliShare.', 'TaurusXi-GuideBackgroundColorAnimation.', 'lawloretienne-ImageGallery.',
     'Bilibili-DanmakuFlameMaster.', 'lawloretienne-DiscreteSlider.', 'graphql-java-graphql-java.',
     'todotxt-todo.txt-android.', 'advantageous-qbit.', 'lawloretienne-Trestle.', 'Bilibili-MagicaSakura.',
     'actorapp-actor-platform.', 'SpongePowered-SpongeAPI.', 'linkedin-rest.li.', 'SpongePowered-SpongeForge.',
     'lawloretienne-QuickReturn.', 'JabRef-jabref.', 'CodelightStudios-Android-Smart-Login.']

b = 'xiongwei-git-AndroidVideoPlayer'
print(b in a)